In [1]:
import gpytorch
import pyreadr
from sklearn import preprocessing
import R_to_python_functions as RPY
#import hyperparameter_runner
import json
import pickle
import sys
import os
import pandas as pd
import numpy as np

In [115]:
#and u[4:] in RPY.get_user_ids()
users = [u for u in os.listdir('data') if 'user' in u and 'pooled' not in u and 'test' not in u  ]
ul = {users[i].strip('user'):i for i in range(len(users))}

In [116]:
result = pyreadr.read_r('data/{}/train.Rdata'.format(users[0]))

In [117]:
uls = [u.strip('user') for u in users]


In [4]:
X = RPY.combine_users('./data',uls)

In [9]:
with open('../../test_new_gpytorch/train_v2_data.pkl','wb') as f:
    pickle.dump(X,f)

In [5]:
with open('../../Downloads/test_params_v2.pkl','rb') as f:
    t = pickle.load(f)

In [131]:
def update_params(users,g,lookup):
    for u in users:
        data_path = 'data/{}/temp_policy.Rdata'.format('user'+u+'_pooled_params')
        #print(data_path)
        
        mu = g[lookup[u]][0]
        sigma = g[lookup[u]][1]
        
        pyreadr.write_rdata(data_path, pd.DataFrame({'mu':mu,'sigma':sigma}))
        

In [134]:
update_params(['10110'],t,ul)

In [128]:
t

{7: (array([-0.07441015,  0.48257828,  0.14194783,  0.04942812,  0.29255771]),
  [array([ 0.21038003, -0.03530982,  0.00111724, -0.04528562,  0.02498912]),
   array([-0.03530982,  0.22338639, -0.03296164, -0.00360989,  0.02996328]),
   array([ 0.00111724, -0.03296164,  0.19748262,  0.01748249,  0.00630283]),
   array([-0.04528562, -0.00360989,  0.01748249,  0.88788516,  0.01023821]),
   array([0.02498912, 0.02996328, 0.00630283, 0.01023821, 0.20387498])]),
 23: (array([-0.07441015,  0.48257828,  0.14194783,  0.04942812,  0.29255771]),
  [array([ 0.21038003, -0.03530982,  0.00111724, -0.04528562,  0.02498912]),
   array([-0.03530982,  0.22338639, -0.03296164, -0.00360989,  0.02996328]),
   array([ 0.00111724, -0.03296164,  0.19748262,  0.01748249,  0.00630283]),
   array([-0.04528562, -0.00360989,  0.01748249,  0.88788516,  0.01023821]),
   array([0.02498912, 0.02996328, 0.00630283, 0.01023821, 0.20387498])])}

In [9]:
from datetime import date
str(date.today())

'2019-09-25'

In [6]:
with open('pooled_init_params.pkl','wb') as f:
    pickle.dump({'sigma_u':np.array([[1.5898, 0.0979],[ 0.0979,    0.6828]]),'noise_term':5.5440},f)

In [10]:
with open('pooled_init_params_all.pkl','wb') as f:
    pickle.dump({str(date.today()):{'sigma_u':np.array([[1.5898, 0.0979],[ 0.0979,    0.6828]]),'noise_term':5.5440}},f)

In [4]:
with open('../../Documents/pooled_hyper_pooled_init_params_2019-09-25.pkl','rb') as f:
    test = pickle.load(f)

In [7]:
test

{'sigma_u': array([[1.5898    , 0.0979    ],
        [0.0979    , 0.68279999]]), 'noise_term': 5.544000148773193}

In [6]:
with open('../../Documents/pooled_init_params.pkl','rb') as f:
    test = pickle.load(f)

In [120]:
df =pd.read_excel('../../Documents/people_join_date.xlsx')

In [121]:
df['Date'] =  pd.to_datetime(df['Date'])


In [122]:
df.index=df['Date']

In [30]:
df['C'] = np.arange(len(df))

In [123]:
df =df.sort_index()

In [124]:
df['C'] = np.arange(len(df))

In [125]:
df

Person       Date   C
Date                             
2019-05-26   10388 2019-05-26   0
2019-06-29   10006 2019-06-29   1
2019-07-04   10296 2019-07-04   2
2019-07-08   10399 2019-07-08   3
2019-07-08   10008 2019-07-08   4
2019-07-18   10027 2019-07-18   5
2019-07-18   10214 2019-07-18   6
2019-07-22   10110 2019-07-22   7
2019-07-25   10327 2019-07-25   8
2019-08-08   10389 2019-08-08   9
2019-08-08   10307 2019-08-08  10
2019-08-09   10342 2019-08-09  11
2019-08-19   10199 2019-08-19  12
2019-08-24   10101 2019-08-24  13
2019-08-24   10055 2019-08-24  14
2019-08-28   10157 2019-08-28  15
2019-08-28   10142 2019-08-28  16
2019-09-01   10178 2019-09-01  17
2019-09-10   10195 2019-09-10  18
2019-09-11   10075 2019-09-11  19
2019-09-12   10237 2019-09-12  20
2019-09-14   10271 2019-09-14  21
2019-09-14   10041 2019-09-14  22
2019-09-23   10355 2019-09-23  23
2019-09-29   10062 2019-09-29  24
2019-09-29   10374 2019-09-29  25
2019-10-07   10215 2019-10-07  26
2019-10-07   10313 2019-10-07  27
2019-10-08   10395 2019-10-08  28
2019-10-09   10152 2019-10-09  29
2019-10-10   10194 2019-10-10  30

In [ ]:
avoids = 10217

In [56]:
for k, v in test.items():
    print(k)
    print(np.diagonal(v[1]))

0
[0.9097351  0.0152902  0.46904329 0.29253298 0.30764391]
1
[0.83290138 0.0152902  0.46904329 0.29253298 0.30764391]
2
[0.97239582 0.0152902  0.46904329 0.29253298 0.30764391]
3
[0.84730452 0.0152902  0.46904329 0.29253298 0.30764391]
4
[0.76845389 0.0152902  0.46904329 0.29253298 0.30764391]
6
[1.11247447 0.0152902  0.46904329 0.29253298 0.30764391]
7
[1.0351125  0.0152902  0.46904329 0.29253298 0.30764391]


In [112]:
with open('../../heartsteps/pooling-service/data/test.pkl','rb') as f:
    test2 = pickle.load(f)


In [113]:
for k, v in test2.items():
    print(k)
    print(np.diagonal(v[1]))
    print(v[0])

0
[0.85649242 1.37575159 0.44339083 0.28323565 0.29727414]
[ 1.19364534 -0.73281458  0.02129793 -0.14994746 -0.05423049]
1
[0.7447458  1.37575159 0.44339083 0.28323565 0.29727414]
[ 1.65444297 -0.73281458  0.02129793 -0.14994746 -0.05423049]
2
[0.92552487 1.37575159 0.44339083 0.28323565 0.29727414]
[-0.28483176 -0.73281458  0.02129793 -0.14994746 -0.05423049]
3
[0.74986118 1.37575159 0.44339083 0.28323565 0.29727414]
[ 0.07717103 -0.73281458  0.02129793 -0.14994746 -0.05423049]
4
[0.70895447 1.37575159 0.44339083 0.28323565 0.29727414]
[-0.02972633 -0.73281458  0.02129793 -0.14994746 -0.05423049]
5
[1.19509299 1.37575159 0.44339083 0.28323565 0.29727414]
[ 0.64180544 -0.73281458  0.02129793 -0.14994746 -0.05423049]
6
[1.03925412 1.37575159 0.44339083 0.28323565 0.29727414]
[ 0.02421209 -0.73281458  0.02129793 -0.14994746 -0.05423049]
7
[0.96330936 1.37575159 0.44339083 0.28323565 0.29727414]
[ 0.02662713 -0.73281458  0.02129793 -0.14994746 -0.05423049]
