In [1]:
import gpytorch
import pyreadr
from sklearn import preprocessing
import R_to_python_functions as RPY
#import hyperparameter_runner
import json
import pickle
import sys
import os
import pandas as pd
import numpy as np

In [2]:
#and u[4:] in RPY.get_user_ids()
users = [u for u in os.listdir('data') if 'user' in u and 'pooled' not in u and 'test' not in u  ]
ul = {users[i].strip('user'):i for i in range(len(users))}

In [3]:
result = pyreadr.read_r('data/{}/train.Rdata'.format(users[0]))

In [4]:
uls = [u.strip('user') for u in users]


In [5]:
len(ul)

32

In [4]:
X = RPY.combine_users('./data',uls)

In [9]:
with open('../../test_new_gpytorch/train_v2_data.pkl','wb') as f:
    pickle.dump(X,f)

In [5]:
with open('../../Downloads/test_params_v2.pkl','rb') as f:
    t = pickle.load(f)

In [131]:
def update_params(users,g,lookup):
    for u in users:
        data_path = 'data/{}/temp_policy.Rdata'.format('user'+u+'_pooled_params')
        #print(data_path)
        
        mu = g[lookup[u]][0]
        sigma = g[lookup[u]][1]
        
        pyreadr.write_rdata(data_path, pd.DataFrame({'mu':mu,'sigma':sigma}))
        

In [134]:
update_params(['10110'],t,ul)

In [128]:
t

{7: (array([-0.07441015,  0.48257828,  0.14194783,  0.04942812,  0.29255771]),
  [array([ 0.21038003, -0.03530982,  0.00111724, -0.04528562,  0.02498912]),
   array([-0.03530982,  0.22338639, -0.03296164, -0.00360989,  0.02996328]),
   array([ 0.00111724, -0.03296164,  0.19748262,  0.01748249,  0.00630283]),
   array([-0.04528562, -0.00360989,  0.01748249,  0.88788516,  0.01023821]),
   array([0.02498912, 0.02996328, 0.00630283, 0.01023821, 0.20387498])]),
 23: (array([-0.07441015,  0.48257828,  0.14194783,  0.04942812,  0.29255771]),
  [array([ 0.21038003, -0.03530982,  0.00111724, -0.04528562,  0.02498912]),
   array([-0.03530982,  0.22338639, -0.03296164, -0.00360989,  0.02996328]),
   array([ 0.00111724, -0.03296164,  0.19748262,  0.01748249,  0.00630283]),
   array([-0.04528562, -0.00360989,  0.01748249,  0.88788516,  0.01023821]),
   array([0.02498912, 0.02996328, 0.00630283, 0.01023821, 0.20387498])])}

In [9]:
from datetime import date
str(date.today())

'2019-09-25'

In [6]:
with open('pooled_init_params.pkl','wb') as f:
    pickle.dump({'sigma_u':np.array([[1.5898, 0.0979],[ 0.0979,    0.6828]]),'noise_term':5.5440},f)

In [10]:
with open('pooled_init_params_all.pkl','wb') as f:
    pickle.dump({str(date.today()):{'sigma_u':np.array([[1.5898, 0.0979],[ 0.0979,    0.6828]]),'noise_term':5.5440}},f)

In [24]:
with open('../../Downloads/pooled_hyper_pooled_init_params_2019-09-25.pkl','rb') as f:
    test = pickle.load(f)

EOFError: Ran out of input

In [22]:
import os
os.getcwd()

'/Users/sabina/heartsteps/pooling-service'